language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer self-update
  - composer install -o

after_deploy:
  - phpunit

services:
  - mongodb
  - redis-server