language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer self-update
  - composer install -o

after_deploy:
  - phpunit

before_install:
  - pecl channel-update pecl.php.net
  - echo '' | pecl install -f mongo